name:
  maximum: 50
email:
  maximum: 255
password:
  minimum: 6
gravatar:
  size: 80
  size_on_show: 30
users:
  avatar: 50
paginate:
  per_page: 10
content:
  maximum: 140
limit: 5
picture:
  limit: 200
expired: 2
